export const mattnedrich = {
  "login": "mattnedrich",
  "id": 4796480,
  "avatar_url": "https://avatars1.githubusercontent.com/u/4796480?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/mattnedrich",
  "html_url": "https://github.com/mattnedrich",
  "followers_url": "https://api.github.com/users/mattnedrich/followers",
  "following_url": "https://api.github.com/users/mattnedrich/following{/other_user}",
  "gists_url": "https://api.github.com/users/mattnedrich/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/mattnedrich/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/mattnedrich/subscriptions",
  "organizations_url": "https://api.github.com/users/mattnedrich/orgs",
  "repos_url": "https://api.github.com/users/mattnedrich/repos",
  "events_url": "https://api.github.com/users/mattnedrich/events{/privacy}",
  "received_events_url": "https://api.github.com/users/mattnedrich/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Matt Nedrich",
  "company": "Atomic Object",
  "blog": "https://spin.atomicobject.com/author/nedrich/",
  "location": "Ann Arbor, MI",
  "email": null,
  "hireable": null,
  "bio": null,
  "public_repos": 27,
  "public_gists": 0,
  "followers": 85,
  "following": 5,
  "created_at": "2013-06-24T06:05:43Z",
  "updated_at": "2017-06-29T10:53:47Z"
};
