export type START_FETCH_USER_PROFILE = 'START_FETCH_USER_PROFILE';
export const  START_FETCH_USER_PROFILE: START_FETCH_USER_PROFILE = 'START_FETCH_USER_PROFILE';

export type FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
export const  FETCH_USER_PROFILE_SUCCESS: FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';

export type FETCH_USER_PROFILE_FAILED = 'FETCH_USER_PROFILE_FAILED';
export const  FETCH_USER_PROFILE_FAILED: FETCH_USER_PROFILE_FAILED = 'FETCH_USER_PROFILE_FAILED';
